### ISSUE TITLE
Update employees and transactions as separate jobs

### ISSUE THREAD

**Issue by arrustamyan** [sflpro/status-check-react#29]
Currently employees and transactions are upserted as part of the same job loop. This has at least two issues:

- we retrieve employees way to frequently, while we can do it once a day
- on first run employees and transactions are sent to the API in parallel, which means there will be transactions that don't match any employees as they have not been inserted yet.

Also in the future we might add more jobs that should run in their own loop.

**Comment by nairihar** [comment]
https://github.com/sflpro/status-check-react/pull/30

**Comment by nairihar** [comment]
closes #30
